package repository
// Package repository provides data access implementations for event registrations.
package repository

import (
	"database/sql"












































































}	return count > 0, nil	}		return false, err	if err != nil {	err := row.Scan(&count)	var count int	row := rr.db.QueryRow(query, eventID, userID)	query := `SELECT COUNT(*) FROM registrations WHERE event_id = ? AND user_id = ?`func (rr *RegistrationRepositoryImpl) IsRegistered(eventID, userID int64) (bool, error) {// IsRegistered checks if a user is registered for an event.}	return eventIDs, rows.Err()	}		eventIDs = append(eventIDs, eventID)		}			return nil, err		if err != nil {		err := rows.Scan(&eventID)		var eventID int64	for rows.Next() {	var eventIDs []int64	defer rows.Close()	}		return nil, err	if err != nil {	rows, err := rr.db.Query(query, userID)	query := `SELECT event_id FROM registrations WHERE user_id = ?`func (rr *RegistrationRepositoryImpl) GetUserRegistrations(userID int64) ([]int64, error) {// GetUserRegistrations retrieves all events a user is registered for.}	return err	_, err = stmt.Exec(eventID, userID)	defer stmt.Close()	}		return err	if err != nil {	stmt, err := rr.db.Prepare(query)	query := `DELETE FROM registrations WHERE event_id = ? AND user_id = ?`func (rr *RegistrationRepositoryImpl) Unregister(eventID, userID int64) error {// Unregister removes a user's registration from an event.}	return err	_, err = stmt.Exec(eventID, userID)	defer stmt.Close()	}		return err	if err != nil {	stmt, err := rr.db.Prepare(query)	query := `INSERT INTO registrations(event_id, user_id) VALUES(?, ?)`func (rr *RegistrationRepositoryImpl) Register(eventID, userID int64) error {// Register registers a user for an event.}	}		BaseRepository: NewBaseRepository(db),	return &RegistrationRepositoryImpl{func NewRegistrationRepository(db *sql.DB) RegistrationRepository {// NewRegistrationRepository creates a new registration repository instance.}	*BaseRepositorytype RegistrationRepositoryImpl struct {// RegistrationRepositoryImpl implements RegistrationRepository interface.)